// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/liushuangls/go-server-template/configs"
	"github.com/liushuangls/go-server-template/internal/cmd"
	"github.com/liushuangls/go-server-template/internal/data"
	"github.com/liushuangls/go-server-template/internal/routes"
	"github.com/liushuangls/go-server-template/internal/routes/v1"
	"github.com/liushuangls/go-server-template/internal/service"
)

// Injectors from wire.go:

func app() (*cmd.App, func(), error) {
	config, err := configs.InitConfig()
	if err != nil {
		return nil, nil, err
	}
	sugaredLogger := cmd.NewLogger(config)
	engine := routes.NewEngine(config)
	client, err := data.NewRedisClient(config)
	if err != nil {
		return nil, nil, err
	}
	limiter := data.NewRedisLimiter(client)
	redislockClient := data.NewRedisLocker(client)
	jwt, err := cmd.NewJwt(config)
	if err != nil {
		return nil, nil, err
	}
	entClient, err := data.NewEntClient(config)
	if err != nil {
		return nil, nil, err
	}
	dataData, cleanup, err := data.NewData(entClient, sugaredLogger, client)
	if err != nil {
		return nil, nil, err
	}
	userRepo := data.NewUserRepo(dataData)
	options := service.Options{
		Log:      sugaredLogger,
		Jwt:      jwt,
		UserRepo: userRepo,
	}
	userService := service.NewUserService(options)
	v1Options := v1.Options{
		Log:         sugaredLogger,
		Limiter:     limiter,
		Locker:      redislockClient,
		UserService: userService,
	}
	userRoute := v1.NewUserRoute(v1Options)
	routesOptions := routes.Options{
		Router:  engine,
		Conf:    config,
		Log:     sugaredLogger,
		Limiter: limiter,
		User:    userRoute,
	}
	httpEngine := routes.NewHttpEngine(routesOptions)
	cmdOptions := cmd.Options{
		Log:  sugaredLogger,
		Http: httpEngine,
	}
	cmdApp := cmd.NewApp(cmdOptions)
	return cmdApp, func() {
		cleanup()
	}, nil
}
