App:
  Addr: ":8082"
  Mode: release
  GeoLite2DB: "resources/bin/GeoLite2-Country.mmdb"

DB:
  Dialect: mysql
  DSN: user:passwd@tcp(127.0.0.1:3306)/database?charset=utf8mb4&parseTime=True&loc=Local
  MaxIdle: 100
  MaxActive: 100
  MaxLifetime: 300
  AutoMigrate: false

Redis:
  Addr: 127.0.0.1:6379
  DB: 0
  Password: ""

Log:
  FileDir: log
  MaxSize: 100
  MaxBackups: 5
  MaxAge: 60
  Compress: false
  LocalTime: false
  AddSource: true

Jwt:
  Secret: "secret_122"
  Issuer: "test.com"

HashID:
  User:
    Type: 0
    Prefix: "U0"
    Salt: "test"

OAuth2:
  Google:
    - ClientID: "xxx"
      Secret: "xxx"
      RedirectURL: "xxx"
      UseSecret: true
      ClientType: web

PublicOSS:
  Platform: aws
  AWS:
    Host: ""
    Bucket: ""
    Region: ""
    AccessKeyID: ""
    AccessKeySecret: ""
